export const techStack = [
  { name: 'React', icon: '/assets/react.svg' },
  { name: 'Next.js', icon: '/assets/nextjs.svg' },
  { name: 'JavaScript', icon: '/assets/javascript.svg' },
  { name: 'TypeScript', icon: '/assets/typescript.svg' },
  { name: 'React Native', icon: '/assets/react-native.svg' },
  { name: 'Vue', icon: '/assets/vue.svg' },
  { name: 'HTML', icon: '/assets/html.svg' },
  { name: 'CSS', icon: '/assets/css.svg' },
  { name: 'Vercel', icon: '/assets/vercel.svg' },
  { name: 'GitHub', icon: '/assets/github.svg' },
  { name: 'Azure DevOps', icon: '/assets/azure.svg' },
  { name: 'TailwindCSS', icon: '/assets/tailwind.svg' },
  { name: 'SCSS', icon: '/assets/scss.svg' },
  { name: 'Node.js', icon: '/assets/nodejs.svg' },
  { name: 'MongoDB', icon: '/assets/mongodb.svg' },
  { name: 'Firebase', icon: '/assets/firebase.svg' },
  { name: 'Supabase', icon: '/assets/supabase.svg' },
  { name: 'Convex', icon: '/assets/convex.svg' },
]